# Generated by Django 5.1.1 on 2024-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_checklist', '0003_alter_user_managers_alter_user_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['model', 'serial_number']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed')], default='Pending', max_length=255),
            preserve_default=False,
        ),
    ]
