# Generated by Django 5.1.1 on 2024-10-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_checklist', '0004_alter_equipment_options_remove_equipment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weekly_checklist.request'),
            preserve_default=False,
        ),
    ]
