# Generated by Django 5.1.1 on 2024-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_checklist', '0005_remove_request_equipment_equipment_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
